# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'react_native_demo_github_app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for react_native_demo_github_app
  pod 'UMCCommon'
  pod 'UMCSecurityPlugins'
  pod 'UMCCommonLog'
  pod 'UMCAnalytics'
  pod 'UMCShare/UI'
  pod 'UMCShare/Social/ReducedWeChat'
  pod 'UMCShare/Social/ReducedQQ'
  pod 'UMCShare/Social/ReducedSina'
  pod 'UMCShare/Social/Email'
  pod 'UMCShare/Social/SMS'

end
